"""0001 initial (week1-3)

Revision ID: 5a294c47c118
Revises: 
Create Date: 2026-06-10 22:49:59.637616

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5a294c47c118'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('useraccount')
    op.drop_table('addresses')
    op.drop_table('role')
    op.drop_table('profileadditionalactivity')
    op.drop_table('profileactivityparent')
    op.drop_table('userregion')
    op.drop_table('passwordresettokens')
    op.drop_table('profileactivity')
    op.drop_table('lga')
    op.drop_table('region')
    op.drop_table('userprofile')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('userprofile',
    sa.Column('createdat', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updatedat', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('deletedat', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('version', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('userprofileid', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('tempclientid', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('userid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('firstname', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('middlename', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('lastname', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('designation', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('gender', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('phonenumber', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('photo', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('roleid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('lgaid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['userid'], ['useraccount.userid'], name=op.f('userprofile_userid_fkey')),
    sa.PrimaryKeyConstraint('userprofileid', name=op.f('userprofile_pkey'))
    )
    op.create_table('region',
    sa.Column('createdat', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updatedat', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('deletedat', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('version', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('regionid', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('tempclientid', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('regionname', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('regionid', name=op.f('region_pkey'))
    )
    op.create_table('lga',
    sa.Column('createdat', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updatedat', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('deletedat', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('version', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('lgaid', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('tempclientid', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('lganame', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('regionid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['regionid'], ['region.regionid'], name=op.f('lga_regionid_fkey')),
    sa.PrimaryKeyConstraint('lgaid', name=op.f('lga_pkey'))
    )
    op.create_table('profileactivity',
    sa.Column('createdat', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updatedat', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('deletedat', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('activityid', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('activityparentid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('activityname', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['activityparentid'], ['profileactivityparent.activityparentid'], name=op.f('profileactivity_activityparentid_fkey')),
    sa.PrimaryKeyConstraint('activityid', name=op.f('profileactivity_pkey'))
    )
    op.create_table('passwordresettokens',
    sa.Column('createdat', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updatedat', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('deletedat', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('userid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('token', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('expiresat', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('isused', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('usedat', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('ipaddress', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('useragent', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['userid'], ['useraccount.userid'], name=op.f('passwordresettokens_userid_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('passwordresettokens_pkey'))
    )
    op.create_table('userregion',
    sa.Column('createdat', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updatedat', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('deletedat', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('version', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('userregionid', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('tempclientid', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('userid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('regionid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['regionid'], ['region.regionid'], name=op.f('userregion_regionid_fkey')),
    sa.ForeignKeyConstraint(['userid'], ['useraccount.userid'], name=op.f('userregion_userid_fkey')),
    sa.PrimaryKeyConstraint('userregionid', name=op.f('userregion_pkey'))
    )
    op.create_table('profileactivityparent',
    sa.Column('createdat', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updatedat', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('deletedat', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('activityparentid', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('activityparentname', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('activityparentid', name=op.f('profileactivityparent_pkey'))
    )
    op.create_table('profileadditionalactivity',
    sa.Column('createdat', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updatedat', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('deletedat', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('additionalactivityid', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('userid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('activityid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('canadd', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('canedit', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('canview', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('candelete', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('canapprove', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('expireon', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['activityid'], ['profileactivity.activityid'], name=op.f('profileadditionalactivity_activityid_fkey')),
    sa.ForeignKeyConstraint(['userid'], ['useraccount.userid'], name=op.f('profileadditionalactivity_userid_fkey')),
    sa.PrimaryKeyConstraint('additionalactivityid', name=op.f('profileadditionalactivity_pkey'))
    )
    op.create_table('role',
    sa.Column('roleid', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('rolename', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('roleid', name=op.f('role_pkey'))
    )
    op.create_table('addresses',
    sa.Column('createdat', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updatedat', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('deletedat', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('version', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('addressid', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('tempclientid', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('streetaddress', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('town', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('postalcode', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('lgaid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('latitude', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('longitude', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('userid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('farmerid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('farmid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['lgaid'], ['lga.lgaid'], name=op.f('addresses_lgaid_fkey')),
    sa.PrimaryKeyConstraint('addressid', name=op.f('addresses_pkey'))
    )
    op.create_table('useraccount',
    sa.Column('createdat', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updatedat', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('deletedat', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('userid', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('tempclientid', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('passwordhash', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('salt', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('status', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('apitoken', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('logincount', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('lastlogindate', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('deactivateddate', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('failedloginattempt', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('securityquestion', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('securityanswer', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('isactive', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('islocked', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('passwordresettoken', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('lastpasswordreset', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('passwordresettokenexpires', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('version', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('lgaid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('userid', name=op.f('useraccount_pkey'))
    )
    # ### end Alembic commands ###
